spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated # 开启生产者发布确认：异步模式。会触发ConfirmCallback回调
    publisher-returns: true # 开启消息回退，消息路由不到合适的队列时，触发ReturnsCallback回调，配合mandatory=true使用
    template:
      mandatory: true # true：消息路由不到合适的队列时，强制触发ReturnsCallback回调。
    listener:
      # 容器类型：默认值为simple，即SimpleMessageListenerContainer。
      type: simple
      simple:
        acknowledge-mode: manual # manual：开启消费端手动ack应答。默认值为auto自动应答。

# 自定义的交换机、队列及绑定键的名称
my:
  rabbitmq:
    topic-exchange-name: boot_topic
    topic-queue-name: boot_topic_queue
    topic-routing-key: boot.#
