spring:
  rabbitmq:
    host: 127.0.0.1 # host
    port: 5672 # 端口号，默认值 5672。
    username: guest # 用户名，默认值 guest。
    password: guest # 密码，默认值 guest。
    virtual-host: / # 虚拟主机，默认值 /。
    publisher-confirm-type: correlated # 开启生产者发布确认：异步模式。会触发 ConfirmCallback 回调。
    publisher-returns: true # 开启消息回退，消息路由不到合适的队列时，触发 ReturnsCallback 回调，配合 RabbitTemplate 的 mandatory=true 使用。
    template:
      mandatory: true # true：消息路由不到合适的队列时，强制触发 ReturnsCallback 回调。
    listener:
      # 容器类型：默认值为 simple，即 SimpleMessageListenerContainer。
      type: simple
      simple:
        acknowledge-mode: manual # manual：开启消费端手动 ack 应答。默认值为 auto 自动应答。
  application:
    name: xuejian-rabbitmq

# 自定义的交换机、队列及绑定键的名称
my:
  rabbitmq:
    topic-exchange-name: boot_topic
    topic-queue-name: boot_topic_queue
    topic-routing-key: boot.#
    normal-exchange-name: normal_exchange
    normal-queue-name: normal_queue
    normal-routing-key: normal.#
    dead-letter-exchange-name: dead_exchange
    dead-letter-queue-name: dead_queue
    dead-letter-routing-key: dead.#
    delayed-exchange-name: delayed_exchange
    delayed-queue-name: delayed_queue
    delayed-routing-key: delayed.#
