server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      # 注意：此处如果是纯数字需要加上双引号
      password: "123456"
  redis:
    host: localhost
    port: 6379
    # 密码默认为空
    password:
    timeout: 5000
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/r2dbc_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
