# 单一属性
title: Spring Boot!

# 多级属性
chunyu:
  user:
    name: 胡歌
    age: 18

# 数组类型
languages:
  - Java
  - Python
  - Go

platforms: [pc, android, ios, mini]

# 变量引用
user-service:
  base-domain: https://domain.com
  urls:
    get-users: ${user-service.base-domain}/getUsers
    add-user: ${user-service.base-domain}/addUser
    update-user: ${user-service.base-domain}/updateUser

# 转义字符
escape-character: "\temp"

server:
  port: 80

spring:
  profiles:
    active: local
  application:
    name: chunyu-configure-application